sonar.projectKey=pes2526q2-12-gei-upc-h_healthy-way-landing
sonar.organization=pes2526q2-12-gei-upc-h
sonar.projectName=Healthy Way - Landing
sonar.host.url=https://sonarcloud.io
sonar.sources=src
sonar.exclusions=node_modules/**,dist/**,public/**
sonar.javascript.node.maxExecutionTime=600
